server:
  port: 2021

#eureka连接信息
eureka:
  instance:
    hostname: summer.com
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: https://zengling:zengling@${eureka.instance.hostname}:10001/eureka/