
server:
  port: 2022

#eureka连接信息
eureka:
  instance:
    hostname: summer.com
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://zengling:zengling@${eureka.instance.hostname}:10002/eureka/