server:
  port: 7002

#eureka连接信息
eureka:
  instance:
    hostname: summer.com
  client:
    enabled: false
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: https://zengling:zengling@${eureka.instance.hostname}:10002/eureka/

spring:
  cloud:
    config:
      #需要从github上读取的资源名称，注意没有yml后缀名
      name: iot-test,iot-job-test
      #本次访问的配置项
      profile: @profiles.active@
      label: master
      #本微服务启动后先去找3344号服务，通过SpringCloudConfig获取GitHub的服务地址
      uri: http://summer.com:2022
