server:
  port: 7003

spring:
  cloud:
    config:
      #需要从github上读取的资源名称，注意没有yml后缀名
      name: iot-test,iot-test-job
      #本次访问的配置项
      profile: @profiles.active@
      label: master
      #本微服务启动后先去找3344号服务，通过SpringCloudConfig获取GitHub的服务地址
      uri: http://summer.com:2022
