server:
  port: 6000

#spring配置
spring:
  autoconfigure:
    #自动化配置 例外处理
    exclude: com.alibaba.druid.spring.boot.autoconfigure.DruidDataSourceAutoConfigure
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    dynamic:
      primary: mysql-adb
      datasource:
        mysql-adb:
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://localhost:3306/news?useSSL=false&useUnicode=true&characterEncoding=utf8&serverTimezone=CTT&&allowPublicKeyRetrieval=true
          username: root
          password: 123456
    #druid相关配置
    druid:
      #监控统计拦截的filters
      filters: stat
      #配置初始化大小/最小/最大
      initial-size: 1
      min-idle: 1
      max-active: 20
      #获取连接等待超时时间
      max-wait: 60000
      #间隔多久进行一次检测，检测需要关闭的空闲连接
      time-between-eviction-runs-millis: 60000
      #一个连接在池中最小生存的时间
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 'x'
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      #打开PSCache，并指定每个连接上PSCache的大小。oracle设为true，mysql设为false。分库分表较多推荐设置为false
      pool-prepared-statements: false
      max-pool-prepared-statement-per-connection-size: 20
  #redis配置
  redis:
    port: 6379
    host: summer.com
    lettuce:
      pool:
        max-active: 8 # 连接池大连接数（使用负值表示没有限制）
        max-idle: 8 # 连接池中的大空闲连接
        min-idle: 0 # 连接池中的小空闲连接
        max-wait: 1000 # 连接池大阻塞等待时间（使用负值表示没有限制）
      shutdown-timeout: 100   # 关闭超时时间

#mybatis配置
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    auto-mapping-behavior: full
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    default-enum-type-handler: org.apache.ibatis.type.EnumOrdinalTypeHandler
  mapper-locations: classpath*:mapper/**/*Mapper.xml
  global-config:
    db-config:
      logic-delete-field: flag
      logic-not-delete-value: 0
      logic-delete-value: 1

















#eureka连接信息
eureka:
  instance:
    hostname: summer.com
  client:
    enabled: false
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: https://zengling:zengling@${eureka.instance.hostname}:10001/eureka/

