server:
  port: 7001

#eureka连接信息

eureka:
  instance:
    hostname: summer.com
  client:
    enabled: false
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: https://zengling:zengling@${eureka.instance.hostname}:10001/eureka/
